steps:
  - name: python:3.12
    entrypoint: bash
    args:
      - -c
      - |
        pip install --upgrade pip
        pip install -r requirements.txt
        python -m black --check app tests
        python -m ruff check app tests
        python -m pytest -v